name: Test Action
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Run my action
        id: my-action
        uses: ./
        with:
          who-to-greet: '@wulfland'

      - name: Output the ans
        run: echo "The answer is ${{ steps..my-action.outputs.answer }}"
